name: DebugBuild

on:
  push:
    branches:
      - master  # 自分のリポジトリのメインブランチ名に合わせてください（mainなど）
  workflow_dispatch: # 手動で実行ボタンを押せるようにする設定（スライドより）

env:
  # ここを自分のソリューションファイルのパスに書き換えます
  SOLUTION_FILE_PATH: DirectXGame/DirectXGame.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64,Configuration=${{ env.CONFIGURATION }}
